name: CD

on:
  push:
    branches:
      - "workflow"

jobs:
  push-to-docker:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      # Build image
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/trotsly/repostatus-api:latest

  deploy:
    needs: push-to-docker
    runs-on: ubuntu-latest
    steps:
      # SSH into the server
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.KEY }}
          script: /bin/bash Scripts/deploy_repostatus_api.sh ghcr.io/trotsly/repostatus-api:latest